/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
#include <m8c.h>
// SwitchInput address and mask defines
#pragma	ioport	SwitchInput_Data_ADDR:	0x4
BYTE			SwitchInput_Data_ADDR;
#pragma	ioport	SwitchInput_DriveMode_0_ADDR:	0x104
BYTE			SwitchInput_DriveMode_0_ADDR;
#pragma	ioport	SwitchInput_DriveMode_1_ADDR:	0x105
BYTE			SwitchInput_DriveMode_1_ADDR;
#pragma	ioport	SwitchInput_DriveMode_2_ADDR:	0x7
BYTE			SwitchInput_DriveMode_2_ADDR;
#pragma	ioport	SwitchInput_GlobalSelect_ADDR:	0x6
BYTE			SwitchInput_GlobalSelect_ADDR;
#pragma	ioport	SwitchInput_IntCtrl_0_ADDR:	0x106
BYTE			SwitchInput_IntCtrl_0_ADDR;
#pragma	ioport	SwitchInput_IntCtrl_1_ADDR:	0x107
BYTE			SwitchInput_IntCtrl_1_ADDR;
#pragma	ioport	SwitchInput_IntEn_ADDR:	0x5
BYTE			SwitchInput_IntEn_ADDR;
#define SwitchInput_MASK 0x1
// LEDOut1 address and mask defines
#pragma	ioport	LEDOut1_Data_ADDR:	0x4
BYTE			LEDOut1_Data_ADDR;
#pragma	ioport	LEDOut1_DriveMode_0_ADDR:	0x104
BYTE			LEDOut1_DriveMode_0_ADDR;
#pragma	ioport	LEDOut1_DriveMode_1_ADDR:	0x105
BYTE			LEDOut1_DriveMode_1_ADDR;
#pragma	ioport	LEDOut1_DriveMode_2_ADDR:	0x7
BYTE			LEDOut1_DriveMode_2_ADDR;
#pragma	ioport	LEDOut1_GlobalSelect_ADDR:	0x6
BYTE			LEDOut1_GlobalSelect_ADDR;
#pragma	ioport	LEDOut1_IntCtrl_0_ADDR:	0x106
BYTE			LEDOut1_IntCtrl_0_ADDR;
#pragma	ioport	LEDOut1_IntCtrl_1_ADDR:	0x107
BYTE			LEDOut1_IntCtrl_1_ADDR;
#pragma	ioport	LEDOut1_IntEn_ADDR:	0x5
BYTE			LEDOut1_IntEn_ADDR;
#define LEDOut1_MASK 0x2
// LEDOut2 address and mask defines
#pragma	ioport	LEDOut2_Data_ADDR:	0x4
BYTE			LEDOut2_Data_ADDR;
#pragma	ioport	LEDOut2_DriveMode_0_ADDR:	0x104
BYTE			LEDOut2_DriveMode_0_ADDR;
#pragma	ioport	LEDOut2_DriveMode_1_ADDR:	0x105
BYTE			LEDOut2_DriveMode_1_ADDR;
#pragma	ioport	LEDOut2_DriveMode_2_ADDR:	0x7
BYTE			LEDOut2_DriveMode_2_ADDR;
#pragma	ioport	LEDOut2_GlobalSelect_ADDR:	0x6
BYTE			LEDOut2_GlobalSelect_ADDR;
#pragma	ioport	LEDOut2_IntCtrl_0_ADDR:	0x106
BYTE			LEDOut2_IntCtrl_0_ADDR;
#pragma	ioport	LEDOut2_IntCtrl_1_ADDR:	0x107
BYTE			LEDOut2_IntCtrl_1_ADDR;
#pragma	ioport	LEDOut2_IntEn_ADDR:	0x5
BYTE			LEDOut2_IntEn_ADDR;
#define LEDOut2_MASK 0x4
// LEDOut3 address and mask defines
#pragma	ioport	LEDOut3_Data_ADDR:	0x4
BYTE			LEDOut3_Data_ADDR;
#pragma	ioport	LEDOut3_DriveMode_0_ADDR:	0x104
BYTE			LEDOut3_DriveMode_0_ADDR;
#pragma	ioport	LEDOut3_DriveMode_1_ADDR:	0x105
BYTE			LEDOut3_DriveMode_1_ADDR;
#pragma	ioport	LEDOut3_DriveMode_2_ADDR:	0x7
BYTE			LEDOut3_DriveMode_2_ADDR;
#pragma	ioport	LEDOut3_GlobalSelect_ADDR:	0x6
BYTE			LEDOut3_GlobalSelect_ADDR;
#pragma	ioport	LEDOut3_IntCtrl_0_ADDR:	0x106
BYTE			LEDOut3_IntCtrl_0_ADDR;
#pragma	ioport	LEDOut3_IntCtrl_1_ADDR:	0x107
BYTE			LEDOut3_IntCtrl_1_ADDR;
#pragma	ioport	LEDOut3_IntEn_ADDR:	0x5
BYTE			LEDOut3_IntEn_ADDR;
#define LEDOut3_MASK 0x8
// LEDOut4 address and mask defines
#pragma	ioport	LEDOut4_Data_ADDR:	0x4
BYTE			LEDOut4_Data_ADDR;
#pragma	ioport	LEDOut4_DriveMode_0_ADDR:	0x104
BYTE			LEDOut4_DriveMode_0_ADDR;
#pragma	ioport	LEDOut4_DriveMode_1_ADDR:	0x105
BYTE			LEDOut4_DriveMode_1_ADDR;
#pragma	ioport	LEDOut4_DriveMode_2_ADDR:	0x7
BYTE			LEDOut4_DriveMode_2_ADDR;
#pragma	ioport	LEDOut4_GlobalSelect_ADDR:	0x6
BYTE			LEDOut4_GlobalSelect_ADDR;
#pragma	ioport	LEDOut4_IntCtrl_0_ADDR:	0x106
BYTE			LEDOut4_IntCtrl_0_ADDR;
#pragma	ioport	LEDOut4_IntCtrl_1_ADDR:	0x107
BYTE			LEDOut4_IntCtrl_1_ADDR;
#pragma	ioport	LEDOut4_IntEn_ADDR:	0x5
BYTE			LEDOut4_IntEn_ADDR;
#define LEDOut4_MASK 0x10
