/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "DBB00.h"
#include "LCD.h"
#include "TachOverridePWM.h"

#endif
