/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
#include <m8c.h>
// Switch address and mask defines
#pragma	ioport	Switch_Data_ADDR:	0x4
BYTE			Switch_Data_ADDR;
#pragma	ioport	Switch_DriveMode_0_ADDR:	0x104
BYTE			Switch_DriveMode_0_ADDR;
#pragma	ioport	Switch_DriveMode_1_ADDR:	0x105
BYTE			Switch_DriveMode_1_ADDR;
#pragma	ioport	Switch_DriveMode_2_ADDR:	0x7
BYTE			Switch_DriveMode_2_ADDR;
#pragma	ioport	Switch_GlobalSelect_ADDR:	0x6
BYTE			Switch_GlobalSelect_ADDR;
#pragma	ioport	Switch_IntCtrl_0_ADDR:	0x106
BYTE			Switch_IntCtrl_0_ADDR;
#pragma	ioport	Switch_IntCtrl_1_ADDR:	0x107
BYTE			Switch_IntCtrl_1_ADDR;
#pragma	ioport	Switch_IntEn_ADDR:	0x5
BYTE			Switch_IntEn_ADDR;
#define Switch_MASK 0x1
// LED1 address and mask defines
#pragma	ioport	LED1_Data_ADDR:	0x4
BYTE			LED1_Data_ADDR;
#pragma	ioport	LED1_DriveMode_0_ADDR:	0x104
BYTE			LED1_DriveMode_0_ADDR;
#pragma	ioport	LED1_DriveMode_1_ADDR:	0x105
BYTE			LED1_DriveMode_1_ADDR;
#pragma	ioport	LED1_DriveMode_2_ADDR:	0x7
BYTE			LED1_DriveMode_2_ADDR;
#pragma	ioport	LED1_GlobalSelect_ADDR:	0x6
BYTE			LED1_GlobalSelect_ADDR;
#pragma	ioport	LED1_IntCtrl_0_ADDR:	0x106
BYTE			LED1_IntCtrl_0_ADDR;
#pragma	ioport	LED1_IntCtrl_1_ADDR:	0x107
BYTE			LED1_IntCtrl_1_ADDR;
#pragma	ioport	LED1_IntEn_ADDR:	0x5
BYTE			LED1_IntEn_ADDR;
#define LED1_MASK 0x2
// LED2 address and mask defines
#pragma	ioport	LED2_Data_ADDR:	0x4
BYTE			LED2_Data_ADDR;
#pragma	ioport	LED2_DriveMode_0_ADDR:	0x104
BYTE			LED2_DriveMode_0_ADDR;
#pragma	ioport	LED2_DriveMode_1_ADDR:	0x105
BYTE			LED2_DriveMode_1_ADDR;
#pragma	ioport	LED2_DriveMode_2_ADDR:	0x7
BYTE			LED2_DriveMode_2_ADDR;
#pragma	ioport	LED2_GlobalSelect_ADDR:	0x6
BYTE			LED2_GlobalSelect_ADDR;
#pragma	ioport	LED2_IntCtrl_0_ADDR:	0x106
BYTE			LED2_IntCtrl_0_ADDR;
#pragma	ioport	LED2_IntCtrl_1_ADDR:	0x107
BYTE			LED2_IntCtrl_1_ADDR;
#pragma	ioport	LED2_IntEn_ADDR:	0x5
BYTE			LED2_IntEn_ADDR;
#define LED2_MASK 0x4
// LED3 address and mask defines
#pragma	ioport	LED3_Data_ADDR:	0x4
BYTE			LED3_Data_ADDR;
#pragma	ioport	LED3_DriveMode_0_ADDR:	0x104
BYTE			LED3_DriveMode_0_ADDR;
#pragma	ioport	LED3_DriveMode_1_ADDR:	0x105
BYTE			LED3_DriveMode_1_ADDR;
#pragma	ioport	LED3_DriveMode_2_ADDR:	0x7
BYTE			LED3_DriveMode_2_ADDR;
#pragma	ioport	LED3_GlobalSelect_ADDR:	0x6
BYTE			LED3_GlobalSelect_ADDR;
#pragma	ioport	LED3_IntCtrl_0_ADDR:	0x106
BYTE			LED3_IntCtrl_0_ADDR;
#pragma	ioport	LED3_IntCtrl_1_ADDR:	0x107
BYTE			LED3_IntCtrl_1_ADDR;
#pragma	ioport	LED3_IntEn_ADDR:	0x5
BYTE			LED3_IntEn_ADDR;
#define LED3_MASK 0x8
// LED4 address and mask defines
#pragma	ioport	LED4_Data_ADDR:	0x4
BYTE			LED4_Data_ADDR;
#pragma	ioport	LED4_DriveMode_0_ADDR:	0x104
BYTE			LED4_DriveMode_0_ADDR;
#pragma	ioport	LED4_DriveMode_1_ADDR:	0x105
BYTE			LED4_DriveMode_1_ADDR;
#pragma	ioport	LED4_DriveMode_2_ADDR:	0x7
BYTE			LED4_DriveMode_2_ADDR;
#pragma	ioport	LED4_GlobalSelect_ADDR:	0x6
BYTE			LED4_GlobalSelect_ADDR;
#pragma	ioport	LED4_IntCtrl_0_ADDR:	0x106
BYTE			LED4_IntCtrl_0_ADDR;
#pragma	ioport	LED4_IntCtrl_1_ADDR:	0x107
BYTE			LED4_IntCtrl_1_ADDR;
#pragma	ioport	LED4_IntEn_ADDR:	0x5
BYTE			LED4_IntEn_ADDR;
#define LED4_MASK 0x10
